browser:
  # window/headless/devtools
  mode: window

  window:
  # browserPath: "C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe"

  devtools:
    port: 21222

  headless:
    args:
      - --disable-canvas-aa
      - --disable-2d-canvas-clip-aa
      - --disable-gl-drawing-for-test
      - --disable-setuid-sandbox
      - --disable-dev-shm-usage
      - --disable-accelerated-2d-canvas
      - --no-first-run
      - --disable-gpu
      - --mute-audio
      - --disable-breakpad
      - --no-zygote
      - --no-sandbox

  prefixTitleWithFirstName: true

server:
# port: 9000

flow:
  - PrepareCycle
  - ClosePopups
  - CheckMaintenance
  - HourlyTrapCheck
  - SoundHorn
  - CheckKingReward
  - UpdateEnvironment

PrepareCycle:
  cycleDelay: 15s

CheckMaintenance:
  maintenanceCycleDelay: 10m

HourlyTrapCheck:
  trapCheckMinutes: 30

CheckKingReward:
  mode: buffer
  maxRetry: 5

UpdateEnvironment:
  modules:
  showLatestHunt: true

FloatingIslands:
  launchPadSetup:
    weapon:
    base:
    charm:
    bait:

  wardenSetup:
    weapon:
    base:
    charm:
    bait:

  paragonSetup:
    base:
    charm:
    bait:

  stayOnIslandAfterTrove: false   # if true, ignore the two configs below:

  leaveLowIslandBeforeHunt: 36    # set to 0 to stay until trove
  leaveHighIslandBeforeHunt: 30   # set to 0 to stay until trove

ValourRift:
  climbingSetup:
    charm:

  eclipseSetup:
    charm:

  climbingUmbraSetup:
    charm:

  eclipseUmbraSetup:
    charm:

  farmingSetup:
    bait:
    charm:

  toggleFireUponEclipse: true
